[package]
name = "passmumbler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
gtk4 = { version = "0.7.3", features = ["v4_2"] }
rofi = "0.3.0"
dirs = "5.0.1"
glob = "0.3.1"
dmenu_facade = "0.3.0"
